### ISSUE TITLE
Add charcoal

### ISSUE THREAD

**Issue by LNJplus** [BlockMen/minetest_next#22]
Please add charcoal.
Is there a reason why not?

**Comment by BlockMen** [comment]
> Is there a reason why not?

I guess not. I think its going to be added soon.

**Comment by LNJplus** [comment]
minetest.register_craftitem("default:charcoal", {
	description = "Charcoal",
	inventory_image = "default_charcoal.png",
	groups = {coal=1},
})

minetest.register_craft({
	type = "fuel",
	recipe = "default:charcoal",
	burntime = 30,
})

minetest.register_craft({
	type = "cooking",
	output = "default:charcoal",
	recipe = "group:tree",
})

The code from your dplus mod.

**Comment by BlockMen** [comment]
Thanks, merged. https://github.com/BlockMen/minetest_next/commit/1f3aebd430db986c4287101c0db3a3e2dbf8bb84
